import type { SkillId } from './pilot-types'

export type CurriculumArea = {
  id: string
  title: string
  stage: string
  reference: string
  summary: string
  skillIds: SkillId[]
  sourceUrl: string
}

// Dz.U. 2024 poz. 996, załącznik nr 1, matematyka, s. 182–196.
// Odczyt oficjalnej kopii CKE: 2026-09-16. Kontekst E8 2027: docs/CURRICULUM.md.
const curriculumUrl = 'https://cke.gov.pl/images/_EGZAMIN_OSMOKLASISTY/2024/komunikaty/D20240996.pdf'

export const curriculumSourceNote: string =
  'Podstawa 2024 wskazana przez CKE dla E8 2027: 29 działów i 36 potwierdzonych punktów. Audyt 34 zadań w pilot-coverage.ts wskazuje częściowe ćwiczenie 23 punktów, nie pełne pokrycie wymagań. Szerokie geometry i fractions nie oznaczają pokrycia działów. VII–VIII.XV może być realizowany po egzaminie.'

export const skillLabels: Record<SkillId, string> = {
  fractions: 'Ułamki zwykłe',
  decimals: 'Ułamki dziesiętne',
  integers: 'Liczby całkowite',
  powers: 'Potęgi',
  roots: 'Pierwiastki',
  percent: 'Procenty',
  expressions: 'Wyrażenia algebraiczne',
  equations: 'Równania',
  proportions: 'Proporcjonalność prosta',
  geometry: 'Geometria płaska',
  solids: 'Bryły',
  coordinates: 'Oś liczbowa i układ współrzędnych',
  statistics: 'Dane i statystyka',
  probability: 'Kombinatoryka i prawdopodobieństwo',
  units: 'Jednostki i ich zamiana',
  'word-problems': 'Zadania tekstowe',
}

// skillIds oznacza związek tematyczny, a nie audyt zadań ani pełne pokrycie.
// Pusta lista oznacza brak bezpośredniej kategorii w obecnym słowniku SkillId.
export const curriculumAreas: CurriculumArea[] = [
  {
    id: 'iv-vi-i',
    title: 'Liczby naturalne w dziesiątkowym układzie pozycyjnym',
    stage: 'IV–VI',
    reference: 'IV–VI.I',
    summary: 'Zapis, oś, porównywanie i zaokrąglanie liczb naturalnych; system rzymski do 3000. Luka: brak osobnej umiejętności dla tego działu.',
    skillIds: [],
    sourceUrl: `${curriculumUrl}#page=183`,
  },
  {
    id: 'iv-vi-ii',
    title: 'Działania na liczbach naturalnych',
    stage: 'IV–VI',
    reference: 'IV–VI.II',
    summary: 'Rachunki, podzielność, liczby pierwsze, NWD/NWW, rozkład na czynniki, kwadraty i sześciany, dzielenie z resztą. Powiązanie z potęgami i ułamkami jest częściowe; nie zastępuje osobnej mapy arytmetyki liczb naturalnych.',
    skillIds: ['powers', 'fractions'],
    sourceUrl: `${curriculumUrl}#page=183`,
  },
  {
    id: 'iv-vi-iii',
    title: 'Liczby całkowite',
    stage: 'IV–VI',
    reference: 'IV–VI.III',
    summary: 'Liczby ujemne w praktyce, oś, wartość bezwzględna, porównywanie i proste rachunki pamięciowe. Wybrane wymaganie w verifiedRequirements nie obejmuje całego działu.',
    skillIds: ['integers', 'coordinates'],
    sourceUrl: `${curriculumUrl}#page=184`,
  },
  {
    id: 'iv-vi-iv',
    title: 'Ułamki zwykłe i dziesiętne',
    stage: 'IV–VI',
    reference: 'IV–VI.IV',
    summary: 'Część całości, iloraz, skracanie, wspólny mianownik, liczby mieszane, oś, rozwinięcia dziesiętne, porównywanie i odtwarzanie całości. Szerokie fractions nie dowodzi pokrycia wszystkich 14 punktów.',
    skillIds: ['fractions', 'decimals'],
    sourceUrl: `${curriculumUrl}#page=184`,
  },
  {
    id: 'iv-vi-v',
    title: 'Działania na ułamkach zwykłych i dziesiętnych',
    stage: 'IV–VI',
    reference: 'IV–VI.V',
    summary: 'Cztery działania, ułamek liczby, kwadraty i sześciany oraz wyrażenia mieszane. Obowiązują ograniczenia mianowników, liczby cyfr i trudności wskazane w punktach 1, 2 i 7; nie odwzorowano całego działu.',
    skillIds: ['fractions', 'decimals', 'powers', 'integers'],
    sourceUrl: `${curriculumUrl}#page=185`,
  },
  {
    id: 'iv-vi-vi',
    title: 'Elementy algebry',
    stage: 'IV–VI',
    reference: 'IV–VI.VI',
    summary: 'Proste wzory i zapis literowy; równania z niewiadomą po jednej stronie, także przez zgadywanie lub działanie odwrotne. Brak osobnych wpisów tych punktów w verifiedRequirements.',
    skillIds: ['expressions', 'equations'],
    sourceUrl: `${curriculumUrl}#page=186`,
  },
  {
    id: 'iv-vi-vii',
    title: 'Proste i odcinki',
    stage: 'IV–VI',
    reference: 'IV–VI.VII',
    summary: 'Punkt, prosta, półprosta, odcinek, równoległość i prostopadłość, pomiar oraz odległość punktu od prostej. Brak osobnych wpisów wymagań; geometry jest tylko szeroką kategorią.',
    skillIds: ['geometry', 'units'],
    sourceUrl: `${curriculumUrl}#page=186`,
  },
  {
    id: 'iv-vi-viii',
    title: 'Kąty',
    stage: 'IV–VI',
    reference: 'IV–VI.VIII',
    summary: 'Budowa, pomiar i rysowanie kątów, rodzaje kątów, kąty wierzchołkowe i przyległe. Brak osobnych wpisów wymagań; szkolnego pomiaru kątomierzem nie należy utożsamiać z przyborami E8.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=186`,
  },
  {
    id: 'iv-vi-ix',
    title: 'Wielokąty, koła i okręgi',
    stage: 'IV–VI',
    reference: 'IV–VI.IX',
    summary: 'Trójkąty i czworokąty, ich kąty i własności, osie symetrii, cięciwa, średnica i promień. Punkty 5 i 6 są potwierdzone także przykładami CKE; geometry nie potwierdza pokrycia pozostałych punktów.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=186`,
  },
  {
    id: 'iv-vi-x',
    title: 'Bryły',
    stage: 'IV–VI',
    reference: 'IV–VI.X',
    summary: 'Rozpoznawanie brył, w tym walca, stożka i kuli, siatki oraz zależności między krawędziami. Rozpoznawanie brył obrotowych nie oznacza wymagania obliczania ich pól i objętości; brak osobnych wpisów tego działu.',
    skillIds: ['solids'],
    sourceUrl: `${curriculumUrl}#page=187`,
  },
  {
    id: 'iv-vi-xi',
    title: 'Obliczenia w geometrii',
    stage: 'IV–VI',
    reference: 'IV–VI.XI',
    summary: 'Kąty, obwody i pola wielokątów, objętość i powierzchnia prostopadłościanu, jednostki pola i objętości. Wpisano punkty 3, 6 i 7; pilot ćwiczy tylko pole trapezu z opisu, objętość prostopadłościanu i zamianę l/ml. Brak pól powierzchni i pełnej pracy z rysunkami.',
    skillIds: ['geometry', 'solids', 'units'],
    sourceUrl: `${curriculumUrl}#page=187`,
  },
  {
    id: 'iv-vi-xii',
    title: 'Obliczenia praktyczne',
    stage: 'IV–VI',
    reference: 'IV–VI.XII',
    summary: 'Proste procenty, zegar, kalendarz, temperatura, długość i masa, skala oraz droga–prędkość–czas. Wpisano punkty 6 i 7; pilot ćwiczy km/m i g/kg. Zegar, kalendarz, skala i ruch nie mają zadań; zmiany temperatury są rachunkami, nie odczytem termometru.',
    skillIds: ['percent', 'units', 'proportions', 'word-problems', 'integers'],
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    id: 'iv-vi-xiii',
    title: 'Elementy statystyki opisowej',
    stage: 'IV–VI',
    reference: 'IV–VI.XIII',
    summary: 'Gromadzenie i porządkowanie danych oraz ich odczytywanie i interpretowanie. Brak osobnych wpisów tych punktów; średnia z klas VII–VIII nie zastępuje tego działu.',
    skillIds: ['statistics'],
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    id: 'iv-vi-xiv',
    title: 'Zadania tekstowe',
    stage: 'IV–VI',
    reference: 'IV–VI.XIV',
    summary: 'Czytanie danych, rysunek pomocniczy, zależności, etapy rozwiązania, zastosowania, weryfikacja wyniku i układanie zadań. Sam wpis punktu 5 nie dowodzi pokrycia pozostałych umiejętności.',
    skillIds: ['word-problems'],
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    id: 'vii-viii-i',
    title: 'Potęgi o podstawach wymiernych',
    stage: 'VII–VIII',
    reference: 'VII–VIII.I',
    summary: 'Zapis iloczynu jako potęgi, działania na potęgach, potęga potęgi i notacja wykładnicza. Wpisano punkty 1, 2 i 4; jedno zadanie pilota ćwiczy dzielenie i potęgę potęgi także przez obliczenie wprost. Brak punktów 3 i 5 w katalogu i brak zadań na notację wykładniczą.',
    skillIds: ['powers'],
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    id: 'vii-viii-ii',
    title: 'Pierwiastki',
    stage: 'VII–VIII',
    reference: 'VII–VIII.II',
    summary: 'Pierwiastki kwadratowe i sześcienne, szacowanie, porównywanie oraz działania i przekształcenia. Wpisano punkty 1 i 4; szacowanie, porównywanie i punkt 5 pozostają poza mapą podpunktów.',
    skillIds: ['roots'],
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    id: 'vii-viii-iii',
    title: 'Tworzenie wyrażeń algebraicznych z jedną i wieloma zmiennymi',
    stage: 'VII–VIII',
    reference: 'VII–VIII.III',
    summary: 'Zapis działań, zależności i rozwiązań zadań wyrażeniami oraz obliczanie ich wartości. Wpisano tylko punkt 2; modelowanie wyrażeniami wymaga dalszego odwzorowania.',
    skillIds: ['expressions', 'word-problems'],
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    id: 'vii-viii-iv',
    title: 'Przekształcanie wyrażeń algebraicznych. Sumy algebraiczne i działania na nich',
    stage: 'VII–VIII',
    reference: 'VII–VIII.IV',
    summary: 'Jednomiany, redukcja wyrazów podobnych, mnożenie sum przez jednomian i dwumianu przez dwumian. Wpisano tylko punkt 2; sama redukcja nie pokrywa mnożenia wyrażeń.',
    skillIds: ['expressions'],
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    id: 'vii-viii-v',
    title: 'Obliczenia procentowe',
    stage: 'VII–VIII',
    reference: 'VII–VIII.V',
    summary: 'Część jako procent, procent liczby, stosunek procentowy, odtwarzanie całości i zastosowania, w tym dwukrotne zmiany. Wpisano punkty 2 i 5; brak pełnego odwzorowania wszystkich wariantów.',
    skillIds: ['percent'],
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    id: 'vii-viii-vi',
    title: 'Równania z jedną niewiadomą',
    stage: 'VII–VIII',
    reference: 'VII–VIII.VI',
    summary: 'Sprawdzanie rozwiązania, równania liniowe i sprowadzalne do liniowych, zadania tekstowe i przekształcanie wzorów. Wpisano punkty 2 i 4; sprawdzanie równań wyższych stopni nie oznacza ogólnego obowiązku ich rozwiązywania.',
    skillIds: ['equations', 'expressions', 'word-problems'],
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    id: 'vii-viii-vii',
    title: 'Proporcjonalność prosta',
    stage: 'VII–VIII',
    reference: 'VII–VIII.VII',
    summary: 'Przykłady wielkości wprost proporcjonalnych, wyznaczanie wartości i podział proporcjonalny. Wpisano punkty 2 i 3; pilot zawiera ceny zeszytów, skalowanie przepisu i podział nasion 2:3. Nie sprawdza samodzielnego podawania przykładów z punktu 1.',
    skillIds: ['proportions'],
    sourceUrl: `${curriculumUrl}#page=191`,
  },
  {
    id: 'vii-viii-viii',
    title: 'Własności figur geometrycznych na płaszczyźnie',
    stage: 'VII–VIII',
    reference: 'VII–VIII.VIII',
    summary: 'Kąty i proste, przystawanie, nierówność trójkąta, Pitagoras bez twierdzenia odwrotnego oraz proste dowody. Wpisano tylko punkt 7; dowodzenie i przystawanie pozostają lukami mapy podpunktów.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=191`,
  },
  {
    id: 'vii-viii-ix',
    title: 'Wielokąty',
    stage: 'VII–VIII',
    reference: 'VII–VIII.IX',
    summary: 'Wielokąty foremne i stosowanie wzorów na pola, także do wyznaczania odcinków, z ograniczeniem trudności do przykładów podstawy. Brak osobnych wpisów tych dwóch punktów.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=192`,
  },
  {
    id: 'vii-viii-x',
    title: 'Oś liczbowa. Układ współrzędnych na płaszczyźnie',
    stage: 'VII–VIII',
    reference: 'VII–VIII.X',
    summary: 'Zbiory na osi, punkty kratowe, środek i długość odcinka oraz punkty na prostej. Wpisano tylko odczyt współrzędnych (punkt 2); nie jest to pokrycie całego działu.',
    skillIds: ['coordinates', 'geometry'],
    sourceUrl: `${curriculumUrl}#page=192`,
  },
  {
    id: 'vii-viii-xi',
    title: 'Geometria przestrzenna',
    stage: 'VII–VIII',
    reference: 'VII–VIII.XI',
    summary: 'Graniastosłupy i ostrosłupy, ich rozpoznawanie, objętości i pola, także brył nieprawidłowych, w granicach podanych przykładów. Brak osobnych wpisów; prostopadłościan z klas IV–VI nie pokrywa tego działu.',
    skillIds: ['solids'],
    sourceUrl: `${curriculumUrl}#page=192`,
  },
  {
    id: 'vii-viii-xii',
    title: 'Wprowadzenie do kombinatoryki i rachunku prawdopodobieństwa',
    stage: 'VII–VIII',
    reference: 'VII–VIII.XII',
    summary: 'Zliczanie obiektów bez konieczności stosowania reguł mnożenia i dodawania oraz proste doświadczenia losowe. Wpisano punkt 2; zliczanie z punktu 1 pozostaje poza mapą podpunktów.',
    skillIds: ['probability'],
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    id: 'vii-viii-xiii',
    title: 'Odczytywanie danych i elementy statystyki opisowej',
    stage: 'VII–VIII',
    reference: 'VII–VIII.XIII',
    summary: 'Interpretowanie tabel, diagramów i wykresów, ich tworzenie oraz średnia arytmetyczna. Wpisano tylko średnią (punkt 3); odczyt i tworzenie prezentacji danych wymagają osobnej mapy.',
    skillIds: ['statistics'],
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    id: 'vii-viii-xiv',
    title: 'Długość okręgu i pole koła',
    stage: 'VII–VIII',
    reference: 'VII–VIII.XIV',
    summary: 'Długość okręgu i pole koła oraz odtwarzanie promienia lub średnicy. Wszystkie cztery punkty odczytano i wpisano; audyt 34 zadań pilota wykazał brak zadań z tego działu. Zezwolenie na realizację po egzaminie dotyczy XV, nie XIV.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    id: 'vii-viii-xv',
    title: 'Symetrie',
    stage: 'VII–VIII',
    reference: 'VII–VIII.XV',
    summary: 'Symetralna, dwusieczna, symetria osiowa i środkowa. Dział może zostać zrealizowany po E8 (Warunki i sposób realizacji, s. 194). Bez wpisów w verifiedRequirements; nie mylić z osiami symetrii w IV–VI.IX.5.',
    skillIds: ['geometry'],
    sourceUrl: `${curriculumUrl}#page=193`,
  },
]

// Potwierdzono istnienie, numerację i treść tych 36 punktów.
// Częściowe użycie w zadaniach opisuje osobno pilot-coverage.ts.
// Cytaty znormalizowano typograficznie; [...] oznacza pominięcie.
// XV (możliwy po egzaminie) pozostaje w mapie działów, nie w tej liście.
export const verifiedRequirements: {
  skillId: SkillId
  reference: string
  excerpt: string
  sourceUrl: string
}[] = [
  {
    skillId: 'fractions',
    reference: 'IV–VI.IV.3',
    excerpt: 'skraca i rozszerza ułamki zwykłe',
    sourceUrl: `${curriculumUrl}#page=184`,
  },
  {
    skillId: 'fractions',
    reference: 'IV–VI.IV.4',
    excerpt: 'sprowadza ułamki zwykłe do wspólnego mianownika',
    sourceUrl: `${curriculumUrl}#page=184`,
  },
  {
    skillId: 'fractions',
    reference: 'IV–VI.IV.12',
    excerpt: 'porównuje ułamki (zwykłe i dziesiętne)',
    sourceUrl: `${curriculumUrl}#page=185`,
  },
  {
    skillId: 'fractions',
    reference: 'IV–VI.V.1',
    excerpt: 'dodaje, odejmuje, mnoży i dzieli ułamki zwykłe o mianownikach jedno- lub dwucyfrowych, a także liczby mieszane',
    sourceUrl: `${curriculumUrl}#page=185`,
  },
  {
    skillId: 'fractions',
    reference: 'IV–VI.V.4',
    excerpt: 'oblicza ułamek danej liczby całkowitej',
    sourceUrl: `${curriculumUrl}#page=185`,
  },
  {
    skillId: 'decimals',
    reference: 'IV–VI.V.2',
    excerpt: 'dodaje, odejmuje, mnoży i dzieli ułamki dziesiętne w pamięci (w przykładach najprostszych), pisemnie (w przypadku gdy ułamki mają razem co najwyżej 6 cyfr różnych od zera) i za pomocą kalkulatora (w przykładach trudniejszych)',
    sourceUrl: `${curriculumUrl}#page=185`,
  },
  {
    skillId: 'integers',
    reference: 'IV–VI.III.5',
    excerpt: 'wykonuje proste rachunki pamięciowe na liczbach całkowitych',
    sourceUrl: `${curriculumUrl}#page=184`,
  },
  {
    skillId: 'powers',
    reference: 'VII–VIII.I.1',
    excerpt: 'zapisuje iloczyn jednakowych czynników w postaci potęgi o wykładniku całkowitym dodatnim',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'powers',
    reference: 'VII–VIII.I.2',
    excerpt: 'mnoży i dzieli potęgi o wykładnikach całkowitych dodatnich',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'powers',
    reference: 'VII–VIII.I.4',
    excerpt: 'podnosi potęgę do potęgi',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'roots',
    reference: 'VII–VIII.II.1',
    excerpt: 'oblicza wartości pierwiastków kwadratowych i sześciennych z liczb, które są odpowiednio kwadratami lub sześcianami liczb wymiernych',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'roots',
    reference: 'VII–VIII.II.4',
    excerpt: 'oblicza pierwiastek z iloczynu i ilorazu dwóch liczb, wyłącza liczbę przed znak pierwiastka i włącza liczbę pod znak pierwiastka',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'percent',
    reference: 'VII–VIII.V.2',
    excerpt: 'oblicza liczbę a równą p procent danej liczby b',
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    skillId: 'percent',
    reference: 'VII–VIII.V.5',
    excerpt: 'stosuje obliczenia procentowe do rozwiązywania problemów w kontekście praktycznym, również w przypadkach dwukrotnych podwyżek lub obniżek danej wielkości',
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    skillId: 'expressions',
    reference: 'VII–VIII.III.2',
    excerpt: 'oblicza wartości liczbowe wyrażeń algebraicznych',
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    skillId: 'expressions',
    reference: 'VII–VIII.IV.2',
    excerpt: 'dodaje i odejmuje sumy algebraiczne, redukując wyrazy podobne',
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    skillId: 'equations',
    reference: 'VII–VIII.VI.2',
    excerpt: 'rozwiązuje równania pierwszego stopnia z jedną niewiadomą metodą równań równoważnych',
    sourceUrl: `${curriculumUrl}#page=190`,
  },
  {
    skillId: 'proportions',
    reference: 'VII–VIII.VII.2',
    excerpt: 'wyznacza wartość przyjmowaną przez wielkość wprost proporcjonalną w przypadku konkretnej zależności proporcjonalnej, np. wartość zakupionego towaru w zależności od liczby sztuk towaru',
    sourceUrl: `${curriculumUrl}#page=191`,
  },
  {
    skillId: 'proportions',
    reference: 'VII–VIII.VII.3',
    excerpt: 'stosuje podział proporcjonalny',
    sourceUrl: `${curriculumUrl}#page=191`,
  },
  {
    skillId: 'geometry',
    reference: 'IV–VI.XI.3',
    excerpt: 'oblicza pola: trójkąta, kwadratu, prostokąta, rombu, równoległoboku, trapezu, przedstawionych na rysunku oraz w sytuacjach praktycznych, w tym także dla danych wymagających zamiany jednostek',
    sourceUrl: `${curriculumUrl}#page=187`,
  },
  {
    skillId: 'geometry',
    reference: 'IV–VI.IX.5',
    excerpt: 'zna najważniejsze własności kwadratu, prostokąta, rombu, równoległoboku i trapezu, rozpoznaje figury osiowosymetryczne i wskazuje osie symetrii figur',
    sourceUrl: `${curriculumUrl}#page=187`,
  },
  {
    skillId: 'geometry',
    reference: 'IV–VI.IX.6',
    excerpt: 'wskazuje na rysunku cięciwę, średnicę oraz promień koła i okręgu',
    sourceUrl: `${curriculumUrl}#page=187`,
  },
  {
    skillId: 'geometry',
    reference: 'VII–VIII.VIII.7',
    excerpt: 'zna i stosuje w sytuacjach praktycznych twierdzenie Pitagorasa (bez twierdzenia odwrotnego)',
    sourceUrl: `${curriculumUrl}#page=191`,
  },
  {
    skillId: 'geometry',
    reference: 'VII–VIII.XIV.1',
    excerpt: 'oblicza długość okręgu o danym promieniu lub danej średnicy',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'geometry',
    reference: 'VII–VIII.XIV.2',
    excerpt: 'oblicza promień lub średnicę okręgu o danej długości okręgu',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'geometry',
    reference: 'VII–VIII.XIV.3',
    excerpt: 'oblicza pole koła o danym promieniu lub danej średnicy',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'geometry',
    reference: 'VII–VIII.XIV.4',
    excerpt: 'oblicza promień lub średnicę koła o danym polu',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'solids',
    reference: 'IV–VI.XI.6',
    excerpt: 'oblicza objętość i pole powierzchni prostopadłościanu przy danych długościach krawędzi',
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    skillId: 'coordinates',
    reference: 'VII–VIII.X.2',
    excerpt: 'znajduje współrzędne danych (na rysunku) punktów kratowych w układzie współrzędnych na płaszczyźnie',
    sourceUrl: `${curriculumUrl}#page=192`,
  },
  {
    skillId: 'statistics',
    reference: 'VII–VIII.XIII.3',
    excerpt: 'oblicza średnią arytmetyczną kilku liczb',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'probability',
    reference: 'VII–VIII.XII.2',
    excerpt: 'przeprowadza proste doświadczenia losowe, polegające na rzucie monetą, rzucie sześcienną kostką do gry, rzucie kostką wielościenną lub losowaniu kuli spośród zestawu kul, analizuje je i oblicza prawdopodobieństwa zdarzeń w doświadczeniach losowych',
    sourceUrl: `${curriculumUrl}#page=193`,
  },
  {
    skillId: 'units',
    reference: 'IV–VI.XII.6',
    excerpt: 'zamienia i prawidłowo stosuje jednostki długości: milimetr, centymetr, decymetr, metr, kilometr',
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    skillId: 'units',
    reference: 'IV–VI.XII.7',
    excerpt: 'zamienia i prawidłowo stosuje jednostki masy: gram, dekagram, kilogram, tona',
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    skillId: 'units',
    reference: 'IV–VI.XI.7',
    excerpt: 'stosuje jednostki objętości i pojemności: cm³, dm³, m³, mililitr, litr',
    sourceUrl: `${curriculumUrl}#page=188`,
  },
  {
    skillId: 'word-problems',
    reference: 'IV–VI.XIV.5',
    excerpt: 'do rozwiązywania zadań osadzonych w kontekście praktycznym stosuje poznaną wiedzę z zakresu arytmetyki i geometrii oraz nabyte umiejętności rachunkowe, a także własne poprawne metody',
    sourceUrl: `${curriculumUrl}#page=189`,
  },
  {
    skillId: 'word-problems',
    reference: 'VII–VIII.VI.4',
    excerpt: 'rozwiązuje zadania tekstowe za pomocą równań pierwszego stopnia z jedną niewiadomą, w tym także z obliczeniami procentowymi',
    sourceUrl: `${curriculumUrl}#page=191`,
  },
]
