import { puzzles } from './adventure'
import type { PilotSession, SkillId } from './pilot-types'

const prologSkills: Record<string, SkillId> = {
  mapa: 'fractions',
  latarnie: 'fractions',
  sklepik: 'decimals',
  bilet: 'fractions',
}

// Rubryki służą ręcznemu przeglądowi zeszytu: 2 punkty robocze, nie skala CKE.
// Diagnoza: UI udostępnia jedną odpowiedź na zadanie, bez podpowiedzi i klucza.
export const pilotSessions: PilotSession[] = [
  {
    id: 'diagnoza-a', title: 'Punkt startu · część A', kind: 'diagnostic',
    week: 1, day: 0, minutes: 25,
    description: 'Sześć krótkich zadań bez fabuły. Zapisuj metody w zeszycie. Do każdego wpisz jedną odpowiedź, bez podpowiedzi. Jeśli nie wiesz, możesz pominąć zadanie.',
    tasks: [
      {
        id: 'diagnoza-a-ulamki', title: 'Różnica ułamków', place: 'Diagnoza A · 1/6',
        skill: 'Odejmowanie ułamków', skillId: 'fractions', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz 7/10 − 1/4. Podaj wynik jako liczbę lub ułamek.',
        expected: '9/20',
        hints: ['Poszukaj wspólnego mianownika.', 'Zapisz oba ułamki w dwudziestych częściach.', '14/20 − 5/20 = 9/20.'],
        solution: ['7/10 = 14/20, a 1/4 = 5/20.', '14/20 − 5/20 = 9/20.'],
        rubric: ['Poprawna metoda odejmowania po sprowadzeniu do wspólnego mianownika (1 pkt).', 'Wynik równoważny 9/20 (1 pkt).'],
        discovery: 'Po diagnozie porównaj zapis w zeszycie z rozwiązaniem.',
      },
      {
        id: 'diagnoza-a-liczby', title: 'Znaki i kolejność', place: 'Diagnoza A · 2/6',
        skill: 'Działania na liczbach całkowitych', skillId: 'integers', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz −6 + 4 · 3. Wpisz jedną liczbę.', expected: '6',
        hints: ['Sprawdź kolejność działań.', 'Najpierw oblicz 4 · 3.', '−6 + 12 = 6.'],
        solution: ['4 · 3 = 12.', '−6 + 12 = 6.'],
        rubric: ['Wykonanie mnożenia przed dodawaniem (1 pkt).', 'Wynik 6 (1 pkt).'],
        discovery: 'Po diagnozie sprawdź kolejność działań w swoim zapisie.',
      },
      {
        id: 'diagnoza-a-potegi', title: 'Potęga potęgi', place: 'Diagnoza A · 3/6',
        skill: 'Potęgowanie i dzielenie potęg', skillId: 'powers', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz (2³)² : 2⁴. Wpisz wartość, nie wyrażenie.', expected: '4',
        hints: ['Możesz obliczyć każdą potęgę osobno.', '(2³)² = 8² = 64, a 2⁴ = 16.', '64 : 16 = 4.'],
        solution: ['(2³)² = 8² = 64; 2⁴ = 16.', '64 : 16 = 4.'],
        rubric: ['Poprawne użycie praw potęg lub obliczenie potęg i zapis ilorazu (1 pkt).', 'Wynik 4 (1 pkt).'],
        discovery: 'Po diagnozie porównaj obliczanie wprost z prawami potęg.',
      },
      {
        id: 'diagnoza-a-pierwiastki', title: 'Dwa pierwiastki', place: 'Diagnoza A · 4/6',
        skill: 'Pierwiastki kwadratowe', skillId: 'roots', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz √144 − √25. Wpisz jedną liczbę.', expected: '7',
        hints: ['Pierwiastki oblicz osobno.', 'Jakie nieujemne liczby podniesione do kwadratu dają 144 i 25?', '√144 = 12, √25 = 5, więc różnica to 7.'],
        solution: ['√144 = 12, ponieważ 12² = 144; √25 = 5, ponieważ 5² = 25.', '12 − 5 = 7.'],
        rubric: ['Poprawne wyznaczenie obu nieujemnych pierwiastków (1 pkt).', 'Wynik 7 (1 pkt).'],
        discovery: 'Po diagnozie sprawdź wartości pierwiastków przez potęgowanie.',
      },
      {
        id: 'diagnoza-a-procenty', title: 'Cena po obniżce', place: 'Diagnoza A · 5/6',
        skill: 'Obniżka procentowa', skillId: 'percent', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Plecak kosztował 160 zł. Cenę obniżono o 15%. Ile złotych kosztuje teraz?',
        expected: '136', unit: 'zł',
        hints: ['Obniżkę licz od 160 zł.', '15% z 160 zł to 24 zł.', '160 − 24 = 136 zł.'],
        solution: ['0,15 · 160 zł = 24 zł.', '160 zł − 24 zł = 136 zł.'],
        rubric: ['Poprawna metoda obliczenia 85% ceny lub odjęcia 15% ceny (1 pkt).', 'Cena 136 zł (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, czy odpowiedź opisuje cenę, czy samą obniżkę.',
      },
      {
        id: 'diagnoza-a-rownanie', title: 'Niewiadoma po obu stronach', place: 'Diagnoza A · 6/6',
        skill: 'Równanie liniowe', skillId: 'equations', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Rozwiąż równanie 3x − 7 = 2x + 8. Wpisz wartość x.', expected: '15',
        hints: ['Odejmij 2x od obu stron.', 'Otrzymasz x − 7 = 8.', 'Dodaj 7 do obu stron: x = 15.'],
        solution: ['3x − 7 = 2x + 8, więc x − 7 = 8.', 'x = 15. Sprawdzenie: 45 − 7 = 30 + 8 = 38.'],
        rubric: ['Poprawne przekształcenia równoważne lub inna uzasadniona metoda wyznaczenia x (1 pkt).', 'Rozwiązanie x = 15 (1 pkt).'],
        discovery: 'Po diagnozie sprawdź wynik przez podstawienie.',
      },
    ],
  },
  {
    id: 'diagnoza-b', title: 'Punkt startu · część B', kind: 'diagnostic',
    week: 1, day: 2, minutes: 25,
    description: 'Kolejne sześć dziedzin. Zapisuj metody w zeszycie. Jedna odpowiedź na zadanie, bez podpowiedzi. To próbka umiejętności, nie prognoza wyniku egzaminu.',
    tasks: [
      {
        id: 'diagnoza-b-pole', title: 'Pole trapezu', place: 'Diagnoza B · 1/6',
        skill: 'Pole trapezu', skillId: 'geometry', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Podstawy trapezu mają długości 6 cm i 10 cm. Wysokość wynosi 4 cm. Oblicz pole w cm².',
        expected: '32', unit: 'cm²',
        hints: ['We wzorze potrzebujesz obu podstaw i wysokości.', 'Pomnóż sumę podstaw przez wysokość i podziel przez 2.', '(6 + 10) · 4 : 2 = 32 cm².'],
        solution: ['P = (6 + 10) · 4 : 2.', 'P = 16 · 4 : 2 = 32 cm².'],
        rubric: ['Poprawne zastosowanie wzoru na pole trapezu lub równoważnej metody (1 pkt).', 'Pole 32 cm² (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, czy użyłaś wysokości, a nie ramienia trapezu.',
      },
      {
        id: 'diagnoza-b-bryla', title: 'Objętość pudełka', place: 'Diagnoza B · 2/6',
        skill: 'Objętość prostopadłościanu', skillId: 'solids', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Prostopadłościan ma długość 5 cm, szerokość 4 cm i wysokość 3 cm. Oblicz jego objętość w cm³.',
        expected: '60', unit: 'cm³',
        hints: ['Objętość to pole podstawy razy wysokość.', 'Pole podstawy wynosi 5 · 4 = 20 cm².', '20 · 3 = 60 cm³.'],
        solution: ['Pole podstawy: 5 · 4 = 20 cm².', 'Objętość: 20 · 3 = 60 cm³.'],
        rubric: ['Poprawna metoda mnożenia trzech wymiarów (1 pkt).', 'Objętość 60 cm³ (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, czy obliczałaś objętość, a nie pole powierzchni.',
      },
      {
        id: 'diagnoza-b-srednia', title: 'Cztery wyniki', place: 'Diagnoza B · 3/6',
        skill: 'Średnia arytmetyczna', skillId: 'statistics', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz średnią arytmetyczną liczb 6, 8, 8, 10.', expected: '8',
        hints: ['Dodaj wszystkie cztery liczby, także powtórzoną ósemkę.', 'Sumę 32 podziel przez liczbę wyników.', '32 : 4 = 8.'],
        solution: ['6 + 8 + 8 + 10 = 32.', '32 : 4 = 8.'],
        rubric: ['Zapis sumy wszystkich czterech wyników podzielonej przez 4 (1 pkt).', 'Średnia 8 (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, ile wyników uwzględniłaś.',
      },
      {
        id: 'diagnoza-b-losowanie', title: 'Jedno losowanie', place: 'Diagnoza B · 4/6',
        skill: 'Prawdopodobieństwo klasyczne', skillId: 'probability', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'W woreczku są 3 niebieskie, 5 czerwonych i 2 zielone kulki. Losujesz jedną; każda kulka ma taką samą szansę. Jakie jest prawdopodobieństwo wylosowania niebieskiej? Podaj liczbę lub ułamek.',
        expected: '3/10',
        hints: ['Policz wszystkie kulki i te niebieskie.', 'Są 3 wyniki sprzyjające spośród 10 jednakowo prawdopodobnych.', 'Prawdopodobieństwo wynosi 3/10.'],
        solution: ['Wszystkich kulek: 3 + 5 + 2 = 10; niebieskich: 3.', 'P = 3/10.'],
        rubric: ['Poprawny stosunek liczby niebieskich kulek do wszystkich kulek (1 pkt).', 'Prawdopodobieństwo równoważne 3/10 (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, czy w mianowniku są wszystkie kulki.',
      },
      {
        id: 'diagnoza-b-proporcja', title: 'Cena zeszytów', place: 'Diagnoza B · 5/6',
        skill: 'Proporcjonalność prosta', skillId: 'proportions', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Cztery jednakowe zeszyty kosztują 14 zł. Cena jednej sztuki jest stała, bez rabatów. Ile kosztuje sześć takich zeszytów?',
        expected: '21', unit: 'zł',
        hints: ['Możesz najpierw obliczyć cenę jednej sztuki.', '14 : 4 = 3,50 zł.', '6 · 3,50 = 21 zł.'],
        solution: ['Jeden zeszyt: 14 zł : 4 = 3,50 zł.', 'Sześć zeszytów: 6 · 3,50 zł = 21 zł.'],
        rubric: ['Poprawne skalowanie ceny w stosunku 6 do 4 lub metoda ceny jednostkowej (1 pkt).', 'Koszt 21 zł (1 pkt).'],
        discovery: 'Po diagnozie sprawdź, czy przeskalowałaś cenę i liczbę sztuk tym samym czynnikiem.',
      },
      {
        id: 'diagnoza-b-wyrazenie', title: 'Wartość wyrażenia', place: 'Diagnoza B · 6/6',
        skill: 'Podstawianie do wyrażenia algebraicznego', skillId: 'expressions', kind: 'transfer',
        story: 'Pracuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz wartość wyrażenia 2(3a − 4) − a dla a = −2.', expected: '-18',
        hints: ['Wstaw −2 w oba miejsca litery a.', 'Otrzymasz 2 · (−6 − 4) − (−2).', '2 · (−10) + 2 = −18.'],
        solution: ['2(3 · (−2) − 4) − (−2) = 2 · (−10) + 2.', '−20 + 2 = −18.'],
        rubric: ['Poprawne podstawienie a = −2 w obu miejscach lub redukcja do 5a − 8 i podstawienie (1 pkt).', 'Wartość −18 (1 pkt).'],
        discovery: 'Po diagnozie zwróć uwagę na odejmowanie liczby ujemnej.',
      },
    ],
  },
  {
    id: 'prolog', title: 'Tajemnica zaginionej strony', kind: 'adventure',
    week: 1, day: 4, minutes: 30,
    description: 'Pierwsza wyprawa z Luną: mapa, latarnie i sklepik Mruka. Trzy zadania fabularne i jedno samodzielne. Metody zapisuj w zeszycie.',
    tasks: puzzles.map((puzzle) => ({ ...puzzle, skillId: prologSkills[puzzle.id] })),
  },
  {
    id: 'lustra', title: 'Dwa odbicia księżyca', kind: 'adventure',
    week: 1, day: 6, minutes: 40,
    description: 'Luna i Mruk szukają dwóch odbić księżyca. Około 30 min na zadania i zapis metod w zeszycie oraz 10 min na rozmowę z rodzicem o sposobach rozwiązania.',
    tasks: [
      {
        id: 'lustra-zaslony', title: 'Odsłonić lustra', place: 'Sala dwóch odbić',
        skill: 'Dodawanie i odejmowanie ułamków', skillId: 'fractions', kind: 'story',
        story: 'Luna znajduje dwa lustra za srebrną tkaniną. Mruk wycina z niej osłony na ramy. „Księżyc lubi wejścia z rozmachem”.',
        prompt: 'Z jednego kawałka tkaniny wycięto 1/6 całości na pierwszą osłonę i 3/8 tej samej całości na drugą. Wycięte części nie nakładają się. Jaka część początkowej tkaniny została? Zapisz metodę w zeszycie.',
        expected: '11/24',
        hints: ['Od całej tkaniny odejmij obie zużyte części.', '1/6 = 4/24, a 3/8 = 9/24. Całość to 24/24.', '24/24 − 4/24 − 9/24 = 11/24.'],
        solution: ['Zużyto 1/6 + 3/8 = 4/24 + 9/24 = 13/24.', 'Zostało 1 − 13/24 = 11/24 tkaniny.'],
        rubric: ['Poprawna metoda odjęcia od całości obu ułamków z właściwym wspólnym mianownikiem (1 pkt).', 'Pozostała część równoważna 11/24 (1 pkt).'],
        discovery: 'Dwa księżyce pojawiają się równocześnie. Między lustrami odsłaniają przycisk windy.',
      },
      {
        id: 'lustra-winda', title: 'Piętra pod i nad ziemią', place: 'Winda między lustrami',
        skill: 'Dodawanie liczb całkowitych', skillId: 'integers', kind: 'story',
        story: 'Mruk wchodzi do windy, Luna wskakuje za nim. Numery poziomów są kolejnymi liczbami całkowitymi, także poniżej zera.',
        prompt: 'Winda rusza z poziomu −4, jedzie o 9 poziomów w górę, a potem o 3 w dół. Na którym poziomie się zatrzyma? Zapisz działanie w zeszycie.',
        expected: '2',
        hints: ['Ruch w górę oznacza dodawanie, w dół — odejmowanie.', 'Po pierwszym ruchu jesteś na poziomie −4 + 9 = 5.', '5 − 3 = 2.'],
        solution: ['−4 + 9 = 5.', '5 − 3 = 2. Winda zatrzyma się na poziomie 2.'],
        rubric: ['Poprawny zapis obu przesunięć od poziomu −4 (1 pkt).', 'Końcowy poziom 2 (1 pkt).'],
        discovery: 'Drzwi otwierają się na balkon. Ponad nim unosi się ogród w chmurach.',
      },
      {
        id: 'lustra-wstazka', title: 'Wstążka do latawca', place: 'Balkon nad archiwum',
        skill: 'Działania na liczbach dziesiętnych', skillId: 'decimals', kind: 'story',
        story: 'Luna wyciąga latawiec, który ma zanieść wiadomość do ogrodu. Mruk wiąże trzy jednakowe wstążki do jego ogona.',
        prompt: 'Z taśmy długości 2,4 m odcięto trzy kawałki po 0,65 m. Nie było innych strat. Ile metrów taśmy zostało? Zapisz obliczenia w zeszycie.',
        expected: '0.45', unit: 'm',
        hints: ['Najpierw oblicz długość trzech odciętych kawałków.', '3 · 0,65 = 1,95 m.', '2,40 − 1,95 = 0,45 m.'],
        solution: ['Odcięto 3 · 0,65 m = 1,95 m.', 'Zostało 2,40 m − 1,95 m = 0,45 m.'],
        rubric: ['Poprawna metoda odjęcia łącznej długości trzech kawałków od długości taśmy (1 pkt).', 'Pozostała długość 0,45 m (1 pkt).'],
        discovery: 'Latawiec wraca ze złotym nasionem. Na bileciku: „Wejście do ogrodu otwiera się o świcie”.',
      },
      {
        id: 'lustra-roznica', title: 'Różne mianowniki', place: 'Samodzielne sprawdzenie',
        skill: 'Odejmowanie ułamków', skillId: 'fractions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz 5/6 − 3/10. Podaj wynik jako liczbę lub ułamek.', expected: '8/15',
        hints: ['Znajdź wspólną wielokrotność 6 i 10.', '5/6 = 25/30, a 3/10 = 9/30.', '25/30 − 9/30 = 16/30 = 8/15.'],
        solution: ['5/6 − 3/10 = 25/30 − 9/30 = 16/30.', '16/30 = 8/15.'],
        rubric: ['Poprawna metoda odejmowania przy wspólnym mianowniku (1 pkt).', 'Wynik równoważny 8/15 (1 pkt; skrócenie nie jest wymagane).'],
        discovery: 'Porównaj w zeszycie odejmowanie ułamków z dodawaniem.',
      },
    ],
  },
  {
    id: 'powrot-1', title: 'Powrót do ułamków i zakupów', kind: 'review',
    week: 2, day: 8, minutes: 25, reviewAfter: { sessionId: 'prolog', days: 3 },
    description: 'Trzy nowe zadania bez fabuły. Zacznij bez zaglądania do wcześniejszych rozwiązań. Metody zapisz w zeszycie; potem sprawdź je z rubryką.',
    tasks: [
      {
        id: 'powrot-1-suma', title: 'Nowa suma', place: 'Powtórka · 1/3',
        skill: 'Dodawanie ułamków', skillId: 'fractions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz 7/15 + 1/6. Podaj wynik jako liczbę lub ułamek.', expected: '19/30',
        hints: ['Poszukaj wspólnego mianownika dla 15 i 6.', 'Możesz użyć 30: 7/15 = 14/30, a 1/6 = 5/30.', '14/30 + 5/30 = 19/30.'],
        solution: ['7/15 + 1/6 = 14/30 + 5/30.', 'Suma wynosi 19/30.'],
        rubric: ['Poprawne sprowadzenie do wspólnego mianownika i metoda dodawania (1 pkt).', 'Wynik równoważny 19/30 (1 pkt).'],
        discovery: 'Sprawdź, czy mianownik opisuje te same części w obu składnikach.',
      },
      {
        id: 'powrot-1-biblioteka', title: 'Książki poza półką', place: 'Powtórka · 2/3',
        skill: 'Ułamek liczby i zmiana liczby obiektów', skillId: 'fractions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Na półce było 35 książek. Wypożyczono 4/7 wszystkich, a później zwrócono 3 z wypożyczonych. Nie było innych wypożyczeń ani zwrotów. Ile książek jest nadal wypożyczonych?',
        expected: '17', unit: 'książek',
        hints: ['Najpierw oblicz, ile książek wypożyczono.', '4/7 z 35 to 20 książek. Zwroty zmniejszają tę liczbę.', '20 − 3 = 17 książek nadal jest wypożyczonych.'],
        solution: ['Wypożyczono 35 : 7 · 4 = 20 książek.', 'Nadal wypożyczonych: 20 − 3 = 17.'],
        rubric: ['Poprawna metoda obliczenia 4/7 z 35, a następnie odjęcia zwrotów (1 pkt).', 'Nadal wypożyczonych 17 książek (1 pkt).'],
        discovery: 'Sprawdź, czy odpowiedź dotyczy książek wypożyczonych, czy stojących na półce.',
      },
      {
        id: 'powrot-1-zakupy', title: 'Reszta z dwudziestu', place: 'Powtórka · 3/3',
        skill: 'Wieloetapowe działania na liczbach dziesiętnych', skillId: 'decimals', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Kupujesz dwa notesy po 6,80 zł i trzy ołówki po 1,45 zł. Płacisz 20 zł. Ile złotych reszty otrzymasz?',
        expected: '2.05', unit: 'zł',
        hints: ['Oblicz osobno koszt notesów i ołówków.', 'Koszty to 13,60 zł i 4,35 zł. Dodaj je.', '20,00 − 17,95 = 2,05 zł.'],
        solution: ['2 · 6,80 zł = 13,60 zł; 3 · 1,45 zł = 4,35 zł.', 'Razem 17,95 zł; reszta: 20,00 zł − 17,95 zł = 2,05 zł.'],
        rubric: ['Poprawna metoda obliczenia kosztu obu rodzajów zakupów i reszty (1 pkt).', 'Reszta 2,05 zł (1 pkt).'],
        discovery: 'Sprawdź wynik: koszt zakupów i reszta powinny dać 20 zł.',
      },
    ],
  },
  {
    id: 'ogrod', title: 'Ogród w chmurach', kind: 'adventure',
    week: 2, day: 9, minutes: 35,
    description: 'Luna i Mruk docierają do ogrodu nad archiwum. Trzy zadania fabularne i jedno bez fabuły. Zapisuj metody w zeszycie, także przeliczenia jednostek.',
    tasks: [
      {
        id: 'ogrod-nasiona', title: 'Dwa kolory rabaty', place: 'Brama ogrodu',
        skill: 'Podział w danym stosunku', skillId: 'proportions', kind: 'story',
        story: 'Złote nasiono otwiera bramę. Luna znajduje plan rabaty, a Mruk rozkłada paczki nasion niebieskich i białych kwiatów.',
        prompt: 'Trzeba wysiać łącznie 30 nasion. Stosunek liczby nasion niebieskich kwiatów do białych ma wynosić 2 : 3. Ile nasion niebieskich kwiatów potrzeba? Zapisz metodę w zeszycie.',
        expected: '12', unit: 'nasion',
        hints: ['Razem jest 2 + 3 równych części.', 'Jedna część to 30 : 5 = 6 nasion.', 'Niebieskie kwiaty to dwie części: 2 · 6 = 12 nasion.'],
        solution: ['2 + 3 = 5 części; 30 : 5 = 6 nasion w części.', 'Niebieskie: 2 · 6 = 12 nasion. Białe: 3 · 6 = 18.'],
        rubric: ['Poprawna metoda podziału całości na 5 równych części i wybrania 2 z nich (1 pkt).', 'Liczba nasion niebieskich kwiatów: 12 (1 pkt).'],
        discovery: 'Kwiaty wyrastają w dwóch kolorach. Wskazują drogę do zbiornika deszczówki.',
      },
      {
        id: 'ogrod-woda', title: 'Deszczówka na zapas', place: 'Szklarnia na chmurze',
        skill: 'Procent liczby i zmiana ilości', skillId: 'percent', kind: 'story',
        story: 'Mruk podlewa rabatę, a Luna ustawia wiadro pod deszczową chmurą. „Tutaj podlewanie działa w obie strony”.',
        prompt: 'W zbiorniku było 80 l wody. Na podlewanie zużyto 25% tej ilości, a potem dolano 6 l. Nie było innych zmian ilości wody. Ile litrów jest teraz w zbiorniku? Zapisz metodę w zeszycie.',
        expected: '66', unit: 'l',
        hints: ['Oblicz 25% początkowych 80 l.', 'Zużyto 20 l. Od 80 odejmij 20 i dodaj 6.', '80 − 20 + 6 = 66 l.'],
        solution: ['25% z 80 l = 1/4 · 80 l = 20 l.', '80 l − 20 l + 6 l = 66 l.'],
        rubric: ['Poprawna metoda obliczenia zużycia od 80 l oraz uwzględnienie dolania (1 pkt).', 'Końcowa ilość 66 l (1 pkt).'],
        discovery: 'W wodzie pojawiają się dwa odbicia księżyca. Między nimi widać drogę do skrzyni.',
      },
      {
        id: 'ogrod-droga', title: 'Droga do skrzyni', place: 'Ścieżka nad chmurami',
        skill: 'Kilometry i metry', skillId: 'units', kind: 'story',
        story: 'Luna biegnie pierwsza, Mruk niesie klucz. Ścieżka ma dwa kolejne odcinki i kończy się przy skrzyni z pieczęcią archiwum.',
        prompt: 'Pierwszy odcinek ścieżki ma 0,75 km, a drugi 180 m. Jaką długość ma cała ścieżka w metrach? Zapisz przeliczenie i działanie w zeszycie.',
        expected: '930', unit: 'm',
        hints: ['Przed dodaniem wyraź obie długości w metrach.', '1 km = 1000 m, więc 0,75 km = 750 m.', '750 + 180 = 930 m.'],
        solution: ['0,75 km = 0,75 · 1000 m = 750 m.', '750 m + 180 m = 930 m.'],
        rubric: ['Poprawne przeliczenie kilometrów na metry i zapis sumy odcinków (1 pkt).', 'Długość ścieżki 930 m (1 pkt).'],
        discovery: 'W skrzyni leży brakujący spis ogrodowych ksiąg. Luna i Mruk zabierają go do Kociego Archiwum.',
      },
      {
        id: 'ogrod-temperatura', title: 'Zmiany temperatury', place: 'Samodzielne sprawdzenie',
        skill: 'Liczby ujemne w kontekście temperatury', skillId: 'integers', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Rano temperatura wynosiła −7°C. Do południa wzrosła o 12°C, a potem spadła o 8°C. Ile stopni Celsjusza wynosiła po tych zmianach?',
        expected: '-3', unit: '°C',
        hints: ['Wzrost dodaj, spadek odejmij.', 'W południe było −7 + 12 = 5°C.', '5 − 8 = −3°C.'],
        solution: ['−7 + 12 = 5.', '5 − 8 = −3. Końcowa temperatura: −3°C.'],
        rubric: ['Poprawny zapis temperatury początkowej i obu zmian ze znakami (1 pkt).', 'Temperatura końcowa −3°C (1 pkt).'],
        discovery: 'Sprawdź, czy temperatura mogła ponownie spaść poniżej zera.',
      },
    ],
  },
  {
    id: 'powrot-2', title: 'Powrót do różnic i znaków', kind: 'review',
    week: 2, day: 11, minutes: 25, reviewAfter: { sessionId: 'lustra', days: 3 },
    description: 'Trzy nowe zadania bez fabuły. Wróć do ułamków, liczb ujemnych i dziesiętnych. Najpierw własna metoda w zeszycie, potem sprawdzenie.',
    tasks: [
      {
        id: 'powrot-2-czesci', title: 'Dwa odejmowania', place: 'Powtórka · 1/3',
        skill: 'Odejmowanie kilku ułamków', skillId: 'fractions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz 9/10 − 1/4 − 1/3. Podaj wynik jako liczbę lub ułamek.', expected: '19/60',
        hints: ['Możesz sprowadzić wszystkie ułamki do jednego mianownika.', 'Użyj 60: otrzymasz 54/60 − 15/60 − 20/60.', '(54 − 15 − 20)/60 = 19/60.'],
        solution: ['9/10 = 54/60; 1/4 = 15/60; 1/3 = 20/60.', '54/60 − 15/60 − 20/60 = 19/60.'],
        rubric: ['Poprawna metoda obu odejmowań ze wspólnym mianownikiem (1 pkt).', 'Wynik równoważny 19/60 (1 pkt).'],
        discovery: 'Sprawdź, czy odjęłaś obie części, a nie ich różnicę.',
      },
      {
        id: 'powrot-2-znaki', title: 'Minus przed nawiasem', place: 'Powtórka · 2/3',
        skill: 'Odejmowanie liczby ujemnej', skillId: 'integers', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Oblicz −14 − (−6) + 11. Wpisz jedną liczbę.', expected: '3',
        hints: ['Odejmowanie liczby ujemnej zastąp dodawaniem liczby przeciwnej.', '−14 − (−6) = −14 + 6 = −8.', '−8 + 11 = 3.'],
        solution: ['−14 − (−6) + 11 = −14 + 6 + 11.', '−8 + 11 = 3.'],
        rubric: ['Poprawne zastąpienie odejmowania −6 dodaniem 6 (1 pkt).', 'Wynik 3 (1 pkt).'],
        discovery: 'Wyjaśnij sobie, dlaczego odjęcie −6 zwiększyło wynik.',
      },
      {
        id: 'powrot-2-masa', title: 'Cztery porcje', place: 'Powtórka · 3/3',
        skill: 'Mnożenie i odejmowanie liczb dziesiętnych', skillId: 'decimals', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Z opakowania zawierającego 1,8 kg ryżu odważono cztery porcje po 0,275 kg. Nic się nie rozsypało. Ile kilogramów ryżu zostało?',
        expected: '0.7', unit: 'kg',
        hints: ['Najpierw policz łączną masę czterech porcji.', '4 · 0,275 = 1,100 kg.', '1,800 − 1,100 = 0,700 kg, czyli 0,7 kg.'],
        solution: ['Odważono 4 · 0,275 kg = 1,1 kg.', 'Zostało 1,8 kg − 1,1 kg = 0,7 kg.'],
        rubric: ['Poprawna metoda obliczenia masy czterech porcji i odjęcia jej od 1,8 kg (1 pkt).', 'Pozostała masa 0,7 kg (1 pkt).'],
        discovery: 'Sprawdź wynik, dodając pozostałą masę do masy odważonych porcji.',
      },
    ],
  },
  {
    id: 'podsumowanie', title: 'Co potrafię przenieść dalej?', kind: 'review',
    week: 2, day: 13, minutes: 35, reviewAfter: { sessionId: 'ogrod', days: 3 },
    description: 'Cztery nowe zadania bez fabuły: około 25 min na pracę i zapis metod w zeszycie oraz 10 min rozmowy z rodzicem. Wybierzcie jeden kolejny temat na podstawie zapisów.',
    tasks: [
      {
        id: 'podsumowanie-zbiornik', title: 'Dwie części pojemności', place: 'Podsumowanie · 1/4',
        skill: 'Suma ułamków i ułamek liczby', skillId: 'fractions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Zbiornik ma pojemność 40 l. Był napełniony do 2/5 pojemności. Dolano wodę równą 1/4 całej pojemności zbiornika. Ile litrów wody jest teraz w środku?',
        expected: '26', unit: 'l',
        hints: ['Oba ułamki dotyczą pełnej pojemności 40 l.', '2/5 + 1/4 = 8/20 + 5/20 = 13/20.', '13/20 z 40 l to 26 l. Możesz też dodać 16 l i 10 l.'],
        solution: ['Początkowo: 2/5 · 40 l = 16 l.', 'Dolano: 1/4 · 40 l = 10 l.', 'Razem: 16 l + 10 l = 26 l.'],
        rubric: ['Poprawna metoda obliczenia obu części tej samej pojemności i ich sumy (1 pkt).', 'Końcowa ilość 26 l (1 pkt).'],
        discovery: 'Sprawdź, czy drugą część liczyłaś od całej pojemności, a nie od początkowej ilości wody.',
      },
      {
        id: 'podsumowanie-obnizki', title: 'Dwie kolejne obniżki', place: 'Podsumowanie · 2/4',
        skill: 'Kolejne zmiany procentowe', skillId: 'percent', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Sweter kosztował 150 zł. Najpierw cenę obniżono o 20%, a potem nową cenę obniżono o 10%. Ile złotych kosztuje po obu obniżkach?',
        expected: '108', unit: 'zł',
        hints: ['Drugi procent licz od ceny po pierwszej obniżce.', 'Po pierwszej obniżce cena wynosi 120 zł. Oblicz 10% ze 120 zł.', 'Druga obniżka to 12 zł, więc cena końcowa wynosi 108 zł.'],
        solution: ['20% z 150 zł = 30 zł; pierwsza cena: 150 zł − 30 zł = 120 zł.', '10% ze 120 zł = 12 zł; końcowa cena: 120 zł − 12 zł = 108 zł.'],
        rubric: ['Poprawna metoda kolejnych obniżek, z drugim procentem liczonym od nowej ceny (1 pkt).', 'Cena końcowa 108 zł (1 pkt).'],
        discovery: 'Sprawdź, dlaczego dodanie 20% i 10% nie opisuje tych dwóch obniżek.',
      },
      {
        id: 'podsumowanie-przepis', title: 'Większa porcja', place: 'Podsumowanie · 3/4',
        skill: 'Proporcjonalność i zamiana gramów na kilogramy', skillId: 'proportions', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'Na 12 jednakowych placuszków potrzeba 300 g mąki. Ilość mąki jest proporcjonalna do liczby placuszków. Ile kilogramów mąki potrzeba na 18 takich placuszków?',
        expected: '0.45', unit: 'kg',
        hints: ['Oblicz ilość mąki na jeden placuszek albo użyj mnożnika 18/12.', '300 : 12 · 18 = 450 g.', '1000 g = 1 kg, więc 450 g = 0,45 kg.'],
        solution: ['Na jeden placuszek: 300 g : 12 = 25 g.', 'Na 18: 25 g · 18 = 450 g = 0,45 kg.'],
        rubric: ['Poprawna metoda proporcjonalnego przeliczenia ilości mąki z 12 na 18 placuszków (1 pkt).', 'Wynik 0,45 kg, uwzględniający zamianę jednostek (1 pkt).'],
        discovery: 'Sprawdź, czy odpowiedź jest w kilogramach, zgodnie z pytaniem.',
      },
      {
        id: 'podsumowanie-pojemnosc', title: 'Ile napoju zostało?', place: 'Podsumowanie · 4/4',
        skill: 'Litry i mililitry', skillId: 'units', kind: 'transfer',
        story: 'Spróbuj samodzielnie. Zapisz metodę w zeszycie.',
        prompt: 'W dzbanku było 1,2 l napoju. Nalano z niego 350 ml do jednego kubka i 425 ml do drugiego. Nic się nie rozlało. Ile mililitrów zostało w dzbanku?',
        expected: '425', unit: 'ml',
        hints: ['Wyraź początkową ilość w mililitrach.', '1,2 l = 1200 ml. Nalano 350 + 425 = 775 ml.', '1200 − 775 = 425 ml.'],
        solution: ['1,2 l = 1200 ml.', '350 ml + 425 ml = 775 ml.', '1200 ml − 775 ml = 425 ml.'],
        rubric: ['Poprawna zamiana litrów na mililitry i metoda odjęcia obu porcji (1 pkt).', 'Pozostała ilość 425 ml (1 pkt).'],
        discovery: 'Z rodzicem porównajcie metody w zeszycie. Wybierzcie jedną rzecz, którą warto jeszcze przećwiczyć.',
      },
    ],
  },
]
